name: log and process issue comments
on: [push]

jobs:
  build:
    steps:
    runs-on: self-hosted
    - name: Test
      uses: dummy-guy-organization/hello-world-typescript-action@2
      with:
        who-to-greet: Naor
