name: log and process issue comments
on: [push]

jobs:
  issue_comment:
    name: log issue comment
    runs-on: self-hosted
    steps:
      - name: Create issue using REST API
        run: |
          echo hi
